# -*- coding: utf-8 -*-
"""House Price Prediction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8KdfF60IDhkiWV4LRhUnAkpXUnhb-Yt

### DATASET :- Housing Prices Dataset
### LINK - https://www.kaggle.com/datasets/yasserh/housing-prices-dataset

The Housing dataset provides both numerical and categorical information about houses. Features such as area, number of bedrooms, bathrooms, parking availability, furnishing status, and location preferences significantly influence house prices, making this dataset suitable for real estate price prediction and regression-based machine learning projects.
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Housing.csv")
df

print(f"Number of rows: {df.shape[0]}, Number of columns: {df.shape[1]}")

print("\nTarget variable: price")
print("Feature variables:")
for col in df.columns:
    if col != 'price':
        print(f"- {col}")

print("\nMissing values per column:")
print(df.isnull().sum())

"""### Data Cleaning"""

# Check for duplicate rows
print(f"Number of duplicate rows before dropping: {df.duplicated().sum()}")

# Remove duplicate rows
df.drop_duplicates(inplace=True)

print(f"Number of duplicate rows after dropping: {df.duplicated().sum()}")
print(f"Number of rows after dropping duplicates: {df.shape[0]}")

# Convert 'yes'/'no' columns to 1/0
yn_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in yn_cols:
    df[col] = df[col].apply(lambda x: 1 if x == 'yes' else 0)

# Perform one-hot encoding for 'furnishingstatus'
df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)

display(df.head())

print("\nDataFrame after cleaning:")
display(df.info())

"""### Task 3 — Model Building"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

"""#### Data Splitting (80/20 train/test)"""

# Define features (X) and target (y)
X = df.drop('price', axis=1)
y = df['price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""#### Linear Regression Model"""

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr = linear_model.predict(X_test)

# Evaluate the model
mae_lr = mean_absolute_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Model Evaluation:")
print(f"  MAE: {mae_lr:.2f}")
print(f"  RMSE: {rmse_lr:.2f}")
print(f"  R-squared: {r2_lr:.2f}")

"""#### Random Forest Regressor Model"""

# Initialize and train the Random Forest Regressor model
rf_model = RandomForestRegressor(random_state=42) # Using a random_state for reproducibility
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regressor Model Evaluation:")
print(f"  MAE: {mae_rf:.2f}")
print(f"  RMSE: {rmse_rf:.2f}")
print(f"  R-squared: {r2_rf:.2f}")

"""#### Model Comparison"""

metrics = {
    'Model': ['Linear Regression', 'Random Forest Regressor'],
    'MAE': [mae_lr, mae_rf],
    'RMSE': [rmse_lr, rmse_rf],
    'R-squared': [r2_lr, r2_rf]
}
comparison_df = pd.DataFrame(metrics)
display(comparison_df)

"""### Task 4 — Visualization

#### Chart 1: Histogram of House Prices
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['price'], kde=True, bins=30)
plt.title('Distribution of House Prices')
plt.xlabel('House Price')
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', alpha=0.6)
plt.savefig('house_price_distribution.png') # Save before showing
plt.show()

"""#### Chart 2: Correlation Heatmap"""

plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Heatmap of Features and Price')
plt.savefig('correlation_heatmap.png') # Save before showing
plt.show()

"""#### Chart 3: Actual vs. Predicted Prices (Linear Regression)"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_lr)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Diagonal line for perfect prediction
plt.title('Actual vs. Predicted House Prices (Linear Regression)')
plt.xlabel('Actual Prices')
plt.ylabel('Predicted Prices')
plt.grid(True, linestyle='--', alpha=0.6)
plt.savefig('actual_vs_predicted_lr.png') # Save before showing
plt.show()

"""### Task 5 — Insights & Summary

Based on our analysis, **area** and **bathrooms** appear to be the most influential features on house price, showing strong positive correlations. Other features like `airconditioning` and `parking` also have notable positive relationships with price, as observed in the correlation heatmap. Our Linear Regression model achieved an R-squared of 0.65, meaning it can explain about 65% of the variance in house prices, which is a reasonable accuracy for a basic model. What might be surprising is the relatively lower influence of `bedrooms` compared to `area` and `bathrooms`. A key recommendation for a real estate business based on these findings is to focus marketing and pricing strategies heavily on the **area and number of bathrooms**, as these are primary drivers of value. Additionally, highlighting amenities like `airconditioning` and ample `parking` can further appeal to potential buyers.
"""